version: "3.2"

services:

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: www
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"